security:
    providers:
        in_memory:
            memory: ~
#        db:
#            entity:
#                class: "AppBundle:User"
#                property: email
#
#    encoders:
#        AppBundle\Entity\User:
#            algorithm: bcrypt
#            cost: 12

    firewalls:

        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|bundles)/
            security: false

        # Disable security for login page
#        login:
#            pattern: ^/login/?$
#            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
#            form_login:
#                login_path:          login
#                check_path:          _login_check
#                default_target_path: admin
#                username_parameter: "appLogin[username]"
#                password_parameter: "appLogin[password]"
#                csrf_parameter:     "appLogin[_token]"
#                csrf_token_id:      authenticate
#                remember_me:        true
#            logout:
#                path:   logout
#                target: login

    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }
